services:
  - type: web
    name: movie-recommendation-system
    env: python
    plan: free
    region: ohio
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
    disk:
      name: movies-data
      mountPath: /data
      sizeGB: 1
